import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
live_config_reload = true

[window]
# decorations = "none"
opacity = 0.85
dynamic_padding = true

[window.dimensions]
columns = 152
lines = 40

[window.padding]
x = 8
y = 8

[scrolling]
history = 100000

[cursor.style]
shape = "Underline"
blinking = "Always"

[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font Mono"
